version: '3.8'
services:
  discord-archiver:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HEADLESS=true
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - CHANNELS=${CHANNELS}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
    volumes:
      - ./data:/app/data
